### ISSUE TITLE
Support for compound tasks?

### ISSUE THREAD

**Issue by sebastianwitthus** [spmeesseman/vscode-taskexplorer#14]
Hi, are you planning on supporting [compound tasks](https://code.visualstudio.com/docs/editor/tasks#_compound-tasks)? They are specified using `dependsOn`

Compound tasks should have their children as leaves in the tree view and their actions – ie `start`/`stop` – could forEach those actions into their children tasks.

**Comment by spmeesseman** [comment]
i can certainly add it to the todo list, i didnt even know these task types existed, very useful!!!

**Comment by spmeesseman** [comment]
ive worked with the compound tasks now and have things to where it works (in 1.14.4), the extension will detect the compound task itself and its child tasks as well since the child tasks are just tasks themselves defined in the tasks array of tasks.json, I didn't see a need to spend time making them child leaves of the compound task.  They are all displayed, and they can all be ran.  Running the compound task will launch the child tasks in parallel, and the child tasks can be ran individually as well.

Now the question was whether or not you could actually define the task within the "dependsOn" array, in which case I could see spending some time making them into child leaves on the tree.  But it doesn't seem like you can do that, you can only define task name strings here.  Please let me know if you know otherwise, and re-open.
