### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by PDKSophia** [spmeesseman/vscode-taskexplorer#143]
The first time I used it, I made a mistake `Maximum call stack size exceeded`

<img src="https://user-images.githubusercontent.com/29560420/109133012-79a7c980-778f-11eb-9e5c-97f0270d8ec1.png" 
 width="500" />

I tried to reopen vscode, but got the same error

<img src="https://user-images.githubusercontent.com/29560420/109133409-f20e8a80-778f-11eb-90a2-80853d840f12.png" 
 width="500" />

**Comment by spmeesseman** [comment]
turn on logging in the extension settings, turn the logging level to "5" in Settings, and reproduce.  Then attach the contents of the log found in the VSCode Output Window (Task Explorer)

**Comment by spmeesseman** [comment]
also, you do have the latest 2.0.4 installed?

**Comment by gusdeuk** [comment]
Hey, same problem here. Hope this helps. It does not happen in all  my projects, just in a couple of them
![image](https://user-images.githubusercontent.com/1907095/109684306-e7247300-7b5e-11eb-89cb-3560abc2873b.png)
Thanks!

**Comment by gusdeuk** [comment]
[I have v2.07] Needed to re-install, v 1.28, then the problem disappears. Thanks! This is a great extension!

**Comment by polmabri** [comment]
Got the same error with version 2.0.0 and 2.0.7 - downgrading to 1.30.2 works.

Thanks for the great extension, too!

**Comment by gchovanyecz** [comment]
+1

**Comment by LeMimit** [comment]
I got the same problem. Got the error when going on the sidebar.  Staying on the waiting status forever.
![image](https://user-images.githubusercontent.com/10245195/110773841-761b4480-825d-11eb-856d-f4e5c09068df.png)

I tried to look at the log. I joined some [logs.txt](https://github.com/spmeesseman/vscode-taskexplorer/files/6122267/logs.txt)

Seems like the discover of the tasks are good and then there is a loop on `*start* remove scripts`, which seems to overflow.

And we got

```console
2021-03-11 10:28:26.607 *start* get tree children
2021-03-11 10:28:26.607    task folder                          : undefined
2021-03-11 10:28:26.607    all tasks need to be retrieved       : false
2021-03-11 10:28:26.607    specific tasks need to be retrieved  : false
2021-03-11 10:28:26.607       current invalidation              : undefined
2021-03-11 10:28:26.607    task tree needs to be built          : true
2021-03-11 10:28:26.607    waiting...
```

And the `waiting...` state stays forever.

Here is my settings for information:

```json
  // Task explorer
  "taskExplorer.enableSideBar": true,
  "taskExplorer.enableAnsiconForAnt": false,
  "taskExplorer.enableAppPublisher": false,
  "taskExplorer.enableGrunt": false,
  "taskExplorer.enableNpm": false,
  "taskExplorer.enableNsis": false,
  "taskExplorer.enablePerl": false,
  "taskExplorer.enableTsc": false,
```
Got VS code `1.54.1` and working with Remote WSL `0.54.2` on a project. May be this is linked that I am using the extension with WSL ?

Hope it can helps to fix this problem. Tell me if you need more information.

I had to go back to version `1.29.0`. To see my tasks. This problem seems to be here since quite some time.

![image](https://user-images.githubusercontent.com/10245195/110774910-9a2b5580-825e-11eb-9673-3bb52014560a.png)

**Comment by spmeesseman** [comment]
thanks for all the info.  ill try to look into this this weekend

**Comment by polmabri** [comment]
fyi: In my case it helped to disable "Group with Separator" in the Task Explorer extension settings

**Comment by danielmeza** [comment]
Group whit separator was the problem, I disable it an it work again
