### ISSUE TITLE
Tasks from npm get overridden by vscode tasks

### ISSUE THREAD

**Issue by MintMissy** [spmeesseman/vscode-taskexplorer#187]
# Missing NPM tasks in the explorer

Angular default run tasks don't show in the npm task explorer menu.
It probably has to do something with their prefixes that go the following:  `start`, `build`, and `test`.

When I change their prefixes they show normally in the explorer menu.

## Task explorer with missing npm tasks
![](https://snipboard.io/DHPT6a.jpg)

## Task explorer after changing task names
![](https://snipboard.io/z3KZRx.jpg)

**Comment by MintMissy** [comment]
I've found the reason why this happens - the vscode tasks override the npm tasks. Is there any way to make them work together?

**Comment by spmeesseman** [comment]
yeah, sorry this is vscode behavior.  TE doesn't own the  task providers for NPM and Workspace tasks, and requests tasks from the internal providers.  I did my own providers for Gulp and Grunt because the internal providers are bad, ive been thinking about doing won provider for NPM too.  seems silly, but maybe someday.  until then yeah this is a behavior that cant be changed
