### ISSUE TITLE
Don't show `Output` window on VSCode start.

### ISSUE THREAD

**Issue by nZeus** [spmeesseman/vscode-taskexplorer#79]
Every time I open VSCode, Task Explorer opens the `Output` window.

Even though I have a setting in VSCode `"debug.internalConsoleOptions": "neverOpen"`.

When I disable Task Explorer, `Output` window is hidden (as expected).

The plugin should not open the `Output` window.

**Comment by spmeesseman** [comment]
It should only show when you first open Code if you had it open when you closed Code last...  Can you verify this is the case?  Or does it show no matter what even if you close Code without the "Output" tab selected?

**Comment by spmeesseman** [comment]
yeah i cannot reproduce this.  please verify my question in the previous post

**Comment by yegor-mialyk** [comment]
Hi @spmeesseman,

It does show every time I open Code.

My steps:
- Open VS Code (no files/folders opened)
- "Output" window appears (with Task Explorer type selected in drop down)
- Close Output window
- Close VS Code
- Reopen VS Code

Actual: "Output" window appears again
Expected: No "Output" window appears.

If I disable Task Explorer extension the issue is gone, which may mean the issue is connected to this extension.

Version: 1.42.1 (user setup)
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:45:59.656Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by yegor-mialyk** [comment]
I think the reason for this issue is that you pass "true" as showOutput in initLog():
https://github.com/spmeesseman/vscode-taskexplorer/blob/c649ef4337f9b9071e4014ae68c64f4d53e6cb60/src/extension.ts#L42

**Comment by spmeesseman** [comment]
aaaahhhh, that was for testing and forgot to remove!!!!

next release...

**Comment by spmeesseman** [comment]
1.24...
